In [1]:
import torch
from torch import nn
import torch.optim as optim
import torch.nn.functional as F

In [2]:
# data 
x_data = torch.tensor([[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], 
                                                        [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]], dtype=torch.float)
# one hot encoding
y_data = torch.tensor([[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]], dtype=torch.float)
# [0, 0, 1]: 2, [0, 1, 0]: 1, [1, 0, 0]: 0

In [3]:
torch.argmax(y_data, dim=1)

tensor([2, 2, 2, 1, 1, 1, 0, 0])

In [4]:
x_data.shape, y_data.shape

(torch.Size([8, 4]), torch.Size([8, 3]))

In [5]:
# parameters
W = torch.zeros([4, 3], requires_grad=True)
b = torch.zeros([3], requires_grad=True)

In [6]:
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)

# training
nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_data @ W + b) # or matmul or @
    cost = nn.BCELoss()(hypothesis, y_data)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.736811
Epoch  200/1000 Cost: 0.669510
Epoch  300/1000 Cost: 0.625964
Epoch  400/1000 Cost: 0.586726
Epoch  500/1000 Cost: 0.544848
Epoch  600/1000 Cost: 0.464968
Epoch  700/1000 Cost: 0.456083
Epoch  800/1000 Cost: 0.453660
Epoch  900/1000 Cost: 0.451666
Epoch 1000/1000 Cost: 0.449987


In [7]:
torch.argmax(torch.sigmoid(x_data @ W + b), axis=1)

tensor([2, 2, 2, 1, 0, 1, 0, 0])

In [8]:
# Example: Zoo dataset
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
zoo = fetch_ucirepo(id=111)
  
# data (as pandas dataframes) 
X = zoo.data.features
y = zoo.data.targets

In [11]:
X

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       1         0     0     1         0        0         1        1   
1       1         0     0     1         0        0         0        1   
2       0         0     1     0         0        1         1        1   
3       1         0     0     1         0        0         1        1   
4       1         0     0     1         0        0         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
96      1         0     0     1         0        0         0        1   
97      1         0     1     0         1        0         0        0   
98      1         0     0     1         0        0         1        1   
99      0         0     1     0         0        0         0        0   
100     0         1     1     0         1        0         0        0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  
0           1         1         0     0     4     0         0        1  
1           1         1         0     0     4     1         0        1  
2           1         0         0     1     0     1         0        0  
3           1         1         0     0     4     0         0        1  
4           1         1         0     0     4     1         0        1  
..        ...       ...       ...   ...   ...   ...       ...      ...  
96          1         1         0     0     2     1         0        1  
97          0         1         1     0     6     0         0        0  
98          1         1         0     0     4     1         0        1  
99          0         1         0     0     0     0         0        0  
100         1         1         0     0     2     1         0        0  

[101 rows x 16 columns]

In [12]:
y

type
0       1
1       1
2       4
3       1
4       1
..    ...
96      1
97      6
98      1
99      7
100     2

[101 rows x 1 columns]

In [9]:
zoo.metadata['abstract'], zoo.metadata['num_instances'], zoo.metadata['num_features']

('Artificial, 7 classes of animals', 101, 16)

In [10]:
max(y.values), min(y.values)

(array([7]), array([1]))

In [13]:
# X -> dataframe to tensor
X_zoo = torch.tensor(X.values, dtype=torch.float)
X_zoo.shape

torch.Size([101, 16])

In [14]:
# y -> dataframe to tensor and one hot encoding
y_zoo = torch.tensor(y.values - 1)
y_hot = F.one_hot(y_zoo.flatten())
y_hot

tensor([[1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0, 0],
        

In [15]:
# parameters
W = torch.zeros((16, 7), requires_grad=True)
b = torch.zeros(7, requires_grad=True)

nn.Softmax()(X_zoo @ W + b)

/root/.pyenv/versions/3.9.2/lib/python3.9/site-packages/torch/nn/modules/module.py:1511: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


tensor([[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0

In [16]:
# training model
W = torch.zeros((16, 7), requires_grad=True)
b = torch.zeros(7, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.1)

# training
nb_epochs = 5000
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.nn.Softmax()(X_zoo @ W + b) # or matmul or @
    cost = torch.nn.BCELoss()(hypothesis, y_hot.type(torch.FloatTensor))

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/5000 Cost: 0.410116
Epoch  100/5000 Cost: 0.231401
Epoch  200/5000 Cost: 0.172228
Epoch  300/5000 Cost: 0.141213
Epoch  400/5000 Cost: 0.122492
Epoch  500/5000 Cost: 0.109689
Epoch  600/5000 Cost: 0.100133
Epoch  700/5000 Cost: 0.092568
Epoch  800/5000 Cost: 0.086333
Epoch  900/5000 Cost: 0.081044
Epoch 1000/5000 Cost: 0.076464
Epoch 1100/5000 Cost: 0.072435
Epoch 1200/5000 Cost: 0.068848
Epoch 1300/5000 Cost: 0.065624
Epoch 1400/5000 Cost: 0.062707
Epoch 1500/5000 Cost: 0.060050
Epoch 1600/5000 Cost: 0.057617
Epoch 1700/5000 Cost: 0.055381
Epoch 1800/5000 Cost: 0.053317
Epoch 1900/5000 Cost: 0.051406
Epoch 2000/5000 Cost: 0.049631
Epoch 2100/5000 Cost: 0.047977
Epoch 2200/5000 Cost: 0.046433
Epoch 2300/5000 Cost: 0.044986
Epoch 2400/5000 Cost: 0.043629
Epoch 2500/5000 Cost: 0.042352
Epoch 2600/5000 Cost: 0.041149
Epoch 2700/5000 Cost: 0.040012
Epoch 2800/5000 Cost: 0.038937
Epoch 2900/5000 Cost: 0.037918
Epoch 3000/5000 Cost: 0.036951
Epoch 3100/5000 Cost: 0.036032
Epoch 32

In [17]:
torch.sum(y_zoo.flatten() == torch.argmax(nn.Softmax()(X_zoo @ W + b), axis=1))

tensor(101)

In [18]:
class Classifier(nn.Module):
    def __init__(self, n_feature, num_classes):
        super().__init__()
        self.num_classes = num_classes
        self.model = nn.Sequential(
            nn.Linear(n_feature, num_classes),
            nn.Softmax()
        )

    def forward(self, x):
        return self.model(x)

    def fit(self, X, y, epochs=1000, lr=0.01, optimizer='SGD', loss='BCELoss', print_every=100):        
        y_hot = nn.functional.one_hot(y.flatten()).type(torch.FloatTensor)

        optimizer = getattr(torch.optim, optimizer)(self.model.parameters(), lr=lr)
        loss_fn = getattr(nn, loss)()
        
        for epoch in range(1, epochs+1):
            optimizer.zero_grad()
            # forward
            pred = self.model(X)
            loss = loss_fn(pred, y_hot)

            # backward
            loss.backward()
            optimizer.step()

            if epoch % print_every == 0:
                print(f'Epoch: [{epoch}/{epochs}], Loss: {loss.item():.4f}', end='\r')

    def predict(self, X):
        return torch.argmax(self.model(X), axis=1)

In [19]:
classifier = Classifier(16, 7)
classifier

Classifier(
  (model): Sequential(
    (0): Linear(in_features=16, out_features=7, bias=True)
    (1): Softmax(dim=None)
  )
)

In [20]:
classifier.fit(X_zoo, y_zoo, epochs=3000, optimizer='Adam', loss='CrossEntropyLoss')

In [22]:
sum(classifier.predict(X_zoo) == y_zoo.flatten())

tensor(101)

In [27]:
class MLPClassifier(nn.Module):
    def __init__(self, n_feature, num_classes, hidden_layers=[64]):
        super().__init__()
        self.num_classes = num_classes
        self.model = nn.Sequential()

        # set hidden layer
        for i in range(len(hidden_layers)):
            if i == 0:
                self.model.append(nn.Linear(n_feature, hidden_layers[i]))
                self.model.append(nn.ReLU())
            else:
                self.model.append(nn.Linear(hidden_layers[i-1], hidden_layers[i]))
                self.model.append(nn.ReLU())

        # set softmax
        self.model.append(nn.Linear(hidden_layers[-1], num_classes))
        self.model.append(nn.Softmax(dim=1))
        

    def forward(self, x):
        return self.model(x)

    def fit(self, X, y, epochs=1000, lr=0.01, optimizer='SGD', loss='BCELoss', print_every=100):        
        y_hot = nn.functional.one_hot(y.flatten()).type(torch.FloatTensor)

        optimizer = getattr(torch.optim, optimizer)(self.model.parameters(), lr=lr)
        loss_fn = getattr(nn, loss)()
        
        for epoch in range(1, epochs+1):
            optimizer.zero_grad()
            
            # forward
            pred = self.model(X)
            loss = loss_fn(pred, y_hot)

            # backward
            loss.backward()
            optimizer.step()

            if epoch % print_every == 0:
                print(f'Epoch: [{epoch}/{epochs}], Loss: {loss.item():.4f}', end='\r')

    def predict(self, X):
        return torch.argmax(self.model(X), axis=1)

In [28]:
classifier = MLPClassifier(16, 7, hidden_layers=[256, 64])
classifier

MLPClassifier(
  (model): Sequential(
    (0): Linear(in_features=16, out_features=256, bias=True)
    (1): ReLU()
    (2): Linear(in_features=256, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=7, bias=True)
    (5): Softmax(dim=1)
  )
)

In [29]:
classifier.fit(X_zoo, y_zoo, epochs=3000, loss='CrossEntropyLoss', optimizer='Adam')
sum(classifier.predict(X_zoo) == y_zoo.flatten())

tensor(101)