In [1]:
import torch

### Scalar
- $a,\ x,\ n$

In [2]:
a = torch.tensor(3.)
a.item()

3.0

### Vector
- $\mathbf{x} \in \mathbb{R}^n$

In [3]:
x = torch.rand(10)
try:
    x.item()
except Exception as err:
    print(err)

x.numpy()

a Tensor with 10 elements cannot be converted to Scalar


array([0.87351483, 0.6533914 , 0.5221987 , 0.1468687 , 0.09732419,
       0.76908386, 0.86155427, 0.81536204, 0.08053774, 0.4656167 ],
      dtype=float32)

In [4]:
y = torch.rand(10)
y

tensor([0.8550, 0.4277, 0.1078, 0.8142, 0.5627, 0.7406, 0.8808, 0.7990, 0.3557,
        0.8215])

In [5]:
torch.matmul(x, y)

tensor(3.6480)

### Matrix
- $\mathbf{A} \in \mathbb{R}^{m\times n}$

In [6]:
A = torch.rand((3,2))
A

tensor([[0.7851, 0.4725],
        [0.7211, 0.6927],
        [0.1305, 0.5888]])

In [7]:
print(f'dimentional: {A.shape}, (row x column): ({A.shape[0]} x {A.shape[1]})')

dimentional: torch.Size([3, 2]), (row x column): (3 x 2)


In [8]:
for i in range(3):
    for j in range(2):
        print(f'A[{i}, {j}]: {A[i, j]:.4f}')

A[0, 0]: 0.7851
A[0, 1]: 0.4725
A[1, 0]: 0.7211
A[1, 1]: 0.6927
A[2, 0]: 0.1305
A[2, 1]: 0.5888


### Matrix Transpose
- $(\mathbf{A}^T)_{i,j}=\mathbf{A}_{j,i}$
- $(\mathbf{A}\mathbf{B})^T=\mathbf{B}^T\mathbf{A}^T$

In [9]:
AT = A.T
AT

tensor([[0.7851, 0.7211, 0.1305],
        [0.4725, 0.6927, 0.5888]])

In [10]:
print(f'dimentional: {AT.shape}, (row x column): ({AT.shape[0]} x {AT.shape[1]})')

dimentional: torch.Size([2, 3]), (row x column): (2 x 3)


In [11]:
for i in range(2):
    for j in range(3):
        print(f'AT[i, j]: {AT[i,j]:.4f}, A[j, i]: {A[j,i]:.4f}')

AT[i, j]: 0.7851, A[j, i]: 0.7851
AT[i, j]: 0.7211, A[j, i]: 0.7211
AT[i, j]: 0.1305, A[j, i]: 0.1305
AT[i, j]: 0.4725, A[j, i]: 0.4725
AT[i, j]: 0.6927, A[j, i]: 0.6927
AT[i, j]: 0.5888, A[j, i]: 0.5888


In [12]:
B = torch.rand((2,3))
B

tensor([[0.0015, 0.0442, 0.5163],
        [0.6601, 0.8956, 0.3602]])

In [13]:
ABT = torch.matmul(A, B).T
BT_AT = torch.matmul(B.T,A.T)

In [14]:
ABT == BT_AT

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### Matrix Product
- $\mathbf{C} = \mathbf{A}\mathbf{B}$
- $C_{i,j} = \sum_k A_{i,k}B_{i,k}$

In [15]:
A = torch.rand((3,2))
B = torch.rand((2,4))
C = torch.matmul(A,B)
C

tensor([[0.8896, 0.4513, 0.1115, 0.8971],
        [0.8735, 0.4742, 0.2380, 1.2804],
        [0.3069, 0.1978, 0.2125, 0.8505]])

In [16]:
print(f'({C.shape[0]} x {C.shape[1]}) = ({A.shape[0]} x {A.shape[1]})({B.shape[0]} x {B.shape[1]})')

(3 x 4) = (3 x 2)(2 x 4)


In [17]:
for i in range(3):
    for j in range(4):
        total = 0
        for k in range(2):
            total += A[i,k]*B[k,j]
        print(f'C[i,j]: {C[i,j]:.4f}, Sum: {total:.4f}')

C[i,j]: 0.8896, Sum: 0.8896
C[i,j]: 0.4513, Sum: 0.4513
C[i,j]: 0.1115, Sum: 0.1115
C[i,j]: 0.8971, Sum: 0.8971
C[i,j]: 0.8735, Sum: 0.8735
C[i,j]: 0.4742, Sum: 0.4742
C[i,j]: 0.2380, Sum: 0.2380
C[i,j]: 1.2804, Sum: 1.2804
C[i,j]: 0.3069, Sum: 0.3069
C[i,j]: 0.1978, Sum: 0.1978
C[i,j]: 0.2125, Sum: 0.2125
C[i,j]: 0.8505, Sum: 0.8505


### Identity Matrix
- $\forall x \in \mathbb{R}^n, \mathbf{I}_n \mathbf{x} = \mathbf{x}$

In [18]:
I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [19]:
x = torch.rand(3)
x

tensor([0.3122, 0.8567, 0.7082])

In [20]:
Ix = torch.matmul(I, x)

In [21]:
Ix == x

tensor([True, True, True])

### Systems of Equations
- $\mathbf{A}\mathbf{x}=\mathbf{b}$
- $\begin{bmatrix} A_{1,1} & A_{1,2} & \cdots & A_{1,n} \\ A_{2,1} & A_{2,2} & \cdots & A_{2,n} \\ & & \vdots \\ A_{m,1} & A_{m,2} & \cdots & A_{m,n}\end{bmatrix} \begin{bmatrix} x_{1} \\ x_{2} \\ \vdots \\ x_{m}  \end{bmatrix}= \begin{bmatrix} A_{1,1}x_{1} + A_{1,2}x_2+ & \cdots &  + A_{1,n}x_{n} \\ A_{2,1}x_{1} + A_{2,2}x_2+ & \cdots &  + A_{2,n}x_{n} \\ & \vdots \\ A_{m,1}x_{1} + A_{m,2}x_2+ & \cdots &  + A_{m,n}x_{n}\end{bmatrix} = \begin{bmatrix} b_{1} \\ b_{2} \\ \vdots \\ b_m\end{bmatrix}$

In [22]:
A = torch.rand(6,7)
A.shape

torch.Size([6, 7])

In [23]:
x = torch.rand(7)
x.shape

torch.Size([7])

In [24]:
b = torch.matmul(A, x)
b

tensor([1.4114, 2.1106, 1.0975, 1.2707, 1.9105, 1.4963])

In [25]:
b_product = []
for m in range(6):
    print(f'b[{m}]: {b[m]:.4f}, {torch.matmul(A[m], x):.4f}') 

b[0]: 1.4114, 1.4114
b[1]: 2.1106, 2.1106
b[2]: 1.0975, 1.0975
b[3]: 1.2707, 1.2707
b[4]: 1.9105, 1.9105
b[5]: 1.4963, 1.4963


### Matrix Inversion
- $\mathbf{A}^{-1}\mathbf{A}=\mathbf{I}_n$
- $\mathbf{A}\mathbf{x} = \mathbf{b} \Rightarrow \mathbf{A}^{-1}\mathbf{A}\mathbf{x}= \mathbf{I}^{n}\mathbf{x}=\mathbf{x}= \mathbf{A}^{-1}\mathbf{b}$

In [26]:
A = torch.rand(3,3)
A

tensor([[0.7642, 0.0637, 0.7053],
        [0.5230, 0.5116, 0.2560],
        [0.4988, 0.8246, 0.8860]])

In [27]:
A_inverse = torch.inverse(A)
A_inverse

tensor([[ 0.8412,  1.8238, -1.1965],
        [-1.1661,  1.1299,  0.6018],
        [ 0.6116, -2.0782,  1.2421]])

In [28]:
torch.matmul(A_inverse, A)

tensor([[ 1.0000e+00, -6.3106e-08, -1.2128e-07],
        [ 9.8881e-08,  1.0000e+00,  1.1889e-07],
        [ 4.4739e-08,  3.4454e-08,  1.0000e+00]])

In [29]:
x = torch.rand(3)
x

tensor([0.7264, 0.7627, 0.6596])

In [30]:
b = torch.matmul(A, x)
b

tensor([1.0689, 0.9389, 1.5756])

In [31]:
torch.matmul(A_inverse, b)

tensor([0.7264, 0.7627, 0.6596])

### Norms
- $||x||_p = (\sum_i |x_i|^p)^{\frac{1}{p}}$
- L1: $||x||_1=\sum_i |x_i|$
- L2: $||x||_2=\sqrt{\sum_i |x_i|^2}$

In [36]:
def norm(arr, p=1):
    return sum([abs(k)**p for k in arr])**(1/p)

In [37]:
x = torch.rand(30)
x

tensor([0.6222, 0.7571, 0.7453, 0.3362, 0.8963, 0.1691, 0.1906, 0.8623, 0.8398,
        0.4851, 0.1398, 0.2417, 0.8130, 0.8870, 0.1354, 0.1888, 0.0792, 0.9531,
        0.1407, 0.7837, 0.6256, 0.3418, 0.7071, 0.7554, 0.1270, 0.1779, 0.2465,
        0.1091, 0.3201, 0.4860])

In [45]:
norm(x.tolist(), p=1), norm(x.tolist(), p=2)

(14.163081347942352, 3.0573725858391354)

In [44]:
torch.norm(x, p=1).item(), torch.norm(x, p=2).item()

(14.163080215454102, 3.057372570037842)