In [1]:
import torch
import numpy as np

# Tensors
## initializing a Tensor
### Ones, Zeros and rand

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
x_np = torch.from_numpy(np.array(data))
x_np

tensor([[1, 2],
        [3, 4]])

In [4]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.5874, 0.2538],
        [0.8537, 0.7065]])

In [6]:
shape = (2,3)
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.3296, 0.2488, 0.6738],
        [0.5763, 0.7046, 0.4513]])

In [7]:
ones_tensor = torch.ones(shape)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
zeros_tensor = torch.zeros(shape)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## Attributes of a Tensor
### Shape

In [9]:
tensor = torch.rand(3,4)
tensor.shape, tensor.dtype, tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

### Slice

In [10]:
# gpu
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
tensor

tensor([[0.4545, 0.1884, 0.1101, 0.8394],
        [0.8243, 0.1715, 0.9009, 0.6041],
        [0.8475, 0.0328, 0.6831, 0.4888]], device='cuda:0')

In [11]:
tensor = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
], dtype=torch.float)
tensor

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

In [12]:
tensor[0]

tensor([1., 2., 3., 4.])

In [13]:
tensor[:, 0]

tensor([ 1.,  5.,  9., 13.])

In [14]:
tensor[...,-1]

tensor([ 4.,  8., 12., 16.])

In [15]:
tensor[:, 1] = 0
tensor

tensor([[ 1.,  0.,  3.,  4.],
        [ 5.,  0.,  7.,  8.],
        [ 9.,  0., 11., 12.],
        [13.,  0., 15., 16.]])

In [16]:
tensor.shape

torch.Size([4, 4])

### Concatenate and Stacking

In [17]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[ 1.,  0.,  3.,  4.,  1.,  0.,  3.,  4.,  1.,  0.,  3.,  4.],
        [ 5.,  0.,  7.,  8.,  5.,  0.,  7.,  8.,  5.,  0.,  7.,  8.],
        [ 9.,  0., 11., 12.,  9.,  0., 11., 12.,  9.,  0., 11., 12.],
        [13.,  0., 15., 16., 13.,  0., 15., 16., 13.,  0., 15., 16.]])

In [18]:
t2 = torch.cat([tensor, tensor, tensor], dim=0)
t2

tensor([[ 1.,  0.,  3.,  4.],
        [ 5.,  0.,  7.,  8.],
        [ 9.,  0., 11., 12.],
        [13.,  0., 15., 16.],
        [ 1.,  0.,  3.,  4.],
        [ 5.,  0.,  7.,  8.],
        [ 9.,  0., 11., 12.],
        [13.,  0., 15., 16.],
        [ 1.,  0.,  3.,  4.],
        [ 5.,  0.,  7.,  8.],
        [ 9.,  0., 11., 12.],
        [13.,  0., 15., 16.]])

In [19]:
t1.shape, t2.shape

(torch.Size([4, 12]), torch.Size([12, 4]))

In [20]:
t3 = torch.stack([tensor, tensor, tensor])
t3

tensor([[[ 1.,  0.,  3.,  4.],
         [ 5.,  0.,  7.,  8.],
         [ 9.,  0., 11., 12.],
         [13.,  0., 15., 16.]],

        [[ 1.,  0.,  3.,  4.],
         [ 5.,  0.,  7.,  8.],
         [ 9.,  0., 11., 12.],
         [13.,  0., 15., 16.]],

        [[ 1.,  0.,  3.,  4.],
         [ 5.,  0.,  7.,  8.],
         [ 9.,  0., 11., 12.],
         [13.,  0., 15., 16.]]])

In [21]:
t4 = torch.stack([tensor, tensor, tensor], dim=1)
t4

tensor([[[ 1.,  0.,  3.,  4.],
         [ 1.,  0.,  3.,  4.],
         [ 1.,  0.,  3.,  4.]],

        [[ 5.,  0.,  7.,  8.],
         [ 5.,  0.,  7.,  8.],
         [ 5.,  0.,  7.,  8.]],

        [[ 9.,  0., 11., 12.],
         [ 9.,  0., 11., 12.],
         [ 9.,  0., 11., 12.]],

        [[13.,  0., 15., 16.],
         [13.,  0., 15., 16.],
         [13.,  0., 15., 16.]]])

In [22]:
t3.shape, t4.shape

(torch.Size([3, 4, 4]), torch.Size([4, 3, 4]))

### Matrix Mulplication

In [23]:
tensor = torch.ones((3,4))
tensor[:, 1] = 0
print(tensor.shape, tensor.T.shape)
y1 = tensor @ tensor.T
y1

torch.Size([3, 4]) torch.Size([4, 3])


tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [24]:
try:
    tensor @ tensor
except Exception as err:
    print(err)

mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)


In [25]:
y2 = tensor.matmul(tensor.T)
y2

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [26]:
try:
    tensor.matmul(tensor)
except Exception as err:
    print(err)

mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)


In [27]:
tensor2 = torch.zeros(3,4)
tensor2[:, 1] = 1
tensor2

tensor([[0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])

In [28]:
# only for same shape
z1 = tensor * tensor2
z1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
try:
    tensor * tensor.T
except Exception as err:
    print(err)

The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1


In [30]:
z3 = torch.rand_like(tensor)
z3

tensor([[0.1863, 0.6782, 0.5466, 0.6368],
        [0.7765, 0.6574, 0.7006, 0.2667],
        [0.2627, 0.3378, 0.0912, 0.6786]])

In [31]:
# out augment
torch.mul(tensor, tensor, out=z3)
z3

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### Sum, Broadcasting, Mean, Max and Argmax

In [32]:
tensor.sum()

tensor(9.)

In [33]:
tensor.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [34]:
# same shape
t1 = torch.tensor([3,3], dtype=torch.float)
t2 = torch.tensor([2,2,], dtype=torch.float)
t1 + t2

tensor([5., 5.])

In [35]:
# vector + scalar
t1 = torch.tensor([1,2], dtype=torch.float)
t2 = torch.tensor([3], dtype=torch.float)
t1 + t2

tensor([4., 5.])

In [36]:
# 2x1 vector + 1x2 vector
t1 = torch.tensor([1,2], dtype=torch.float)
t2 = torch.tensor([[3],[4]], dtype=torch.float)
t1 + t2

tensor([[4., 5.],
        [5., 6.]])

In [37]:
# mean
t = torch.tensor([1,2], dtype=torch.float)
t.mean()

tensor(1.5000)

In [38]:
t = torch.tensor([1,2], dtype=torch.long)
try:
    t.mean()
except Exception as err:
    print(err)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [39]:
t = torch.tensor([[1,2], [3,4]], dtype=torch.float)
t

tensor([[1., 2.],
        [3., 4.]])

In [40]:
t.mean(), t.mean(dim=0), t.mean(dim=1), t.mean(dim=-1)

(tensor(2.5000),
 tensor([2., 3.]),
 tensor([1.5000, 3.5000]),
 tensor([1.5000, 3.5000]))

In [41]:
t.sum(), t.sum(dim=0), t.sum(dim=1), t.sum(dim=-1)

(tensor(10.), tensor([4., 6.]), tensor([3., 7.]), tensor([3., 7.]))

In [42]:
t.max(), t.max(dim=0), t.max(dim=1), t.max(dim=-1)

(tensor(4.),
 torch.return_types.max(
 values=tensor([3., 4.]),
 indices=tensor([1, 1])),
 torch.return_types.max(
 values=tensor([2., 4.]),
 indices=tensor([1, 1])),
 torch.return_types.max(
 values=tensor([2., 4.]),
 indices=tensor([1, 1])))

In [43]:
t = torch.eye(4)
t[:, 1] = 0
t

tensor([[1., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [44]:
t.argmax(), t.argmax(dim=0), t.argmax(dim=1), t.argmax(dim=-1)

(tensor(0), tensor([0, 0, 2, 3]), tensor([0, 0, 2, 3]), tensor([0, 0, 2, 3]))

### Bridge with NumPy
- CPU 상의 텐서는 메모리 위치를 공유해서 사용

In [45]:
t = torch.ones(5)
n = t.numpy()
t, n

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [46]:
t.add_(1)
t, n

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [47]:
n = np.ones(5)
t = torch.from_numpy(n)
t, n

(tensor([1., 1., 1., 1., 1.], dtype=torch.float64),
 array([1., 1., 1., 1., 1.]))

In [48]:
np.add(n, 1, out=n)
t, n

(tensor([2., 2., 2., 2., 2.], dtype=torch.float64),
 array([2., 2., 2., 2., 2.]))

In [49]:
t = torch.ones(5).to('cuda')
t

tensor([1., 1., 1., 1., 1.], device='cuda:0')

In [50]:
# numpy() is not available at cuda device
try:
    t.numpy()
except Exception as err:
    print(err)

can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.


In [51]:
n = t.cpu().numpy()

In [52]:
t.add_(1)
t, n

(tensor([2., 2., 2., 2., 2.], device='cuda:0'),
 array([1., 1., 1., 1., 1.], dtype=float32))

### Squeeze and Unsqueeze

In [57]:
t = torch.tensor([[0],[1],[2]], dtype=torch.float)
print(t)
print(t.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [58]:
print(t.squeeze())
t.squeeze().shape

tensor([0., 1., 2.])


torch.Size([3])

In [59]:
t = torch.tensor([0, 1,2], dtype=torch.float)
print(t)
t.shape

tensor([0., 1., 2.])


torch.Size([3])

In [60]:
print(t.unsqueeze(0))
t.unsqueeze(0).shape

tensor([[0., 1., 2.]])


torch.Size([1, 3])

In [61]:
t.view(1,-1)

tensor([[0., 1., 2.]])

In [62]:
t.unsqueeze(1)

tensor([[0.],
        [1.],
        [2.]])

### Type Casting

In [64]:
lt = torch.tensor([1,2,3,4], dtype=torch.long)
lt

tensor([1, 2, 3, 4])

In [66]:
lt.float()

tensor([1., 2., 3., 4.])

In [68]:
bt = torch.tensor([True, False, False, True], dtype=torch.uint8)
bt

tensor([1, 0, 0, 1], dtype=torch.uint8)

In [69]:
print(bt.long())
bt.float()

tensor([1, 0, 0, 1])


tensor([1., 0., 0., 1.])