In [1]:
import torch
from torch import nn

In [2]:
# AND 
X = torch.tensor([[0,0], [0,1], [1,0], [1,1]], dtype=torch.float)
y_and = torch.tensor([[0],[0],[0],[1]], dtype=torch.float)

In [3]:
class AND(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(2, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

In [4]:
and_model = AND()
and_model

AND(
  (model): Sequential(
    (0): Linear(in_features=2, out_features=1, bias=True)
    (1): Sigmoid()
  )
)

In [14]:
def get_loss_fn(name):
    if name.lower() == 'bce':
        return nn.BCELoss()
    if name.lower() == 'mse':
        return nn.MSELoss()

def get_optimizer(name):
    if name.lower() == 'sgd':
        return torch.optim.SGD
    if name.lower() == 'adam':
        return torch.optim.Adam

def train(x, y, epochs=100, lr=1, loss='bce', optimizer='sgd', model=None):
    if not model:
        return

    optimizer = get_optimizer(optimizer)(model.parameters(), lr=lr)
    loss_fn = get_loss_fn(loss)

    for epoch in range(epochs):
        # grad 초기화
        optimizer.zero_grad()

        # forward
        hypothesis = model(x)

        # check loss 
        error = loss_fn(hypothesis, y)

        # backward - backpropagation
        error.backward()

        # update parameters
        optimizer.step()
        
        if epoch % 100 == 0:
            print(f'Epoch: {epoch}, loss: {error.item()}')

In [15]:
def predict(x, model=None):
    if model:
        return model(x).item()

In [16]:
train(X, y_and, epochs=1000, loss='mse', model=and_model)

Epoch: 0, loss: 0.0003647788835223764
Epoch: 100, loss: 0.0003618058399297297
Epoch: 200, loss: 0.0003588852705433965
Epoch: 300, loss: 0.0003560142358765006
Epoch: 400, loss: 0.0003531845868565142
Epoch: 500, loss: 0.0003503971383906901
Epoch: 600, loss: 0.00034765456803143024
Epoch: 700, loss: 0.00034495495492592454
Epoch: 800, loss: 0.0003422950394451618
Epoch: 900, loss: 0.00033967511262744665


In [17]:
for x in X:
    print(x, predict(x, model=and_model))

tensor([0., 0.]) 9.957033398677595e-06
tensor([0., 1.]) 0.019893981516361237
tensor([1., 0.]) 0.019893962889909744
tensor([1., 1.]) 0.9764025211334229


In [18]:
# OR
y_or = torch.tensor([[0],[1],[1],[1]], dtype=torch.float)

In [19]:
class OR(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(2, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)
        
or_model = OR()
or_model

OR(
  (model): Sequential(
    (0): Linear(in_features=2, out_features=1, bias=True)
    (1): Sigmoid()
  )
)

In [21]:
train(X, y_or, epochs=1000, loss='mse', model=or_model)

Epoch: 0, loss: 0.18817102909088135
Epoch: 100, loss: 0.03419904783368111
Epoch: 200, loss: 0.01719905063509941
Epoch: 300, loss: 0.011048768647015095
Epoch: 400, loss: 0.008011008612811565
Epoch: 500, loss: 0.0062335398979485035
Epoch: 600, loss: 0.00507810153067112
Epoch: 700, loss: 0.00427148537710309
Epoch: 800, loss: 0.0036786722484976053
Epoch: 900, loss: 0.0032257779967039824


In [23]:
for x in X:
    print(x, predict(x, model=or_model))

tensor([0., 0.]) 0.08052095025777817
tensor([0., 1.]) 0.9500356912612915
tensor([1., 0.]) 0.950034499168396
tensor([1., 1.]) 0.9997578263282776


In [39]:
for i, layer in enumerate(or_model.named_parameters()):
    name, param = layer
    print(f'{int(i/2)+1}th layer - name: {name}, parameter: {param}')

1th layer - name: model.0.weight, parameter: Parameter containing:
tensor([[5.3805, 5.3805]], requires_grad=True)
1th layer - name: model.0.bias, parameter: Parameter containing:
tensor([-2.4353], requires_grad=True)
