In [1]:
import torch
from torch import nn

In [17]:
X = torch.tensor([[0,0], [0,1], [1,0], [1,1]], dtype=torch.float)
Y = torch.tensor([[0],[1],[1],[0]], dtype=torch.float)

In [18]:
linear = nn.Linear(2,1)
sigmoid = nn.Sigmoid()

In [19]:
model = nn.Sequential(linear, sigmoid)
model

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
  (1): Sigmoid()
)

In [20]:
loss_fn = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [21]:
# training
epochs = 10000
for epoch in range(1, epochs+1):
    optimizer.zero_grad()
    hypothesis = model(X)
    loss = loss_fn(hypothesis, Y)
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f'Epoch: {epoch}, Loss: {loss.item()}')

Epoch: 100, Loss: 0.698178231716156
Epoch: 200, Loss: 0.6954285502433777
Epoch: 300, Loss: 0.6941826343536377
Epoch: 400, Loss: 0.693617582321167
Epoch: 500, Loss: 0.6933610439300537
Epoch: 600, Loss: 0.6932445764541626
Epoch: 700, Loss: 0.6931914687156677
Epoch: 800, Loss: 0.6931672692298889
Epoch: 900, Loss: 0.693156361579895
Epoch: 1000, Loss: 0.6931514143943787
Epoch: 1100, Loss: 0.6931490898132324
Epoch: 1200, Loss: 0.6931480169296265
Epoch: 1300, Loss: 0.6931475400924683
Epoch: 1400, Loss: 0.6931473612785339
Epoch: 1500, Loss: 0.6931473016738892
Epoch: 1600, Loss: 0.6931472420692444
Epoch: 1700, Loss: 0.6931473016738892
Epoch: 1800, Loss: 0.6931471824645996
Epoch: 1900, Loss: 0.6931471824645996
Epoch: 2000, Loss: 0.6931471824645996
Epoch: 2100, Loss: 0.6931471824645996
Epoch: 2200, Loss: 0.6931471824645996
Epoch: 2300, Loss: 0.6931471824645996
Epoch: 2400, Loss: 0.6931471824645996
Epoch: 2500, Loss: 0.6931471824645996
Epoch: 2600, Loss: 0.6931472420692444
Epoch: 2700, Loss: 0.693

In [14]:
def predict(x, model=None):
    if model:
        return model(x).item()

In [22]:
for x in X:
    print(x, predict(x, model=model))

tensor([0., 0.]) 0.5
tensor([0., 1.]) 0.5
tensor([1., 0.]) 0.5
tensor([1., 1.]) 0.5
